### ISSUE TITLE
卒業制作アプリMVPリリースのレビューをよろしくお願いします。

### ISSUE THREAD

**Issue by rapidcplus** [rapidcplus/ECS_4#11]
### 本当にギリギリの提出となってしまい大変申し訳ありません。
[ここ](https://github.com/rapidcplus/Emergency_Call_Support/issues/7#issuecomment-2113975047)からissueを作成しなおしました。
レビューをよろしくお願いします。

プラットフォームとして動画のストックができる状況にはなっています。
しかし、当初予定してたAPIも未実装です。。。
本リリースに向けて、また頑張っていきたいです。
レビューよろしくお願いします。

_また当初レビューを依頼していた、「ECS開発プロジェクト」から実際のリモートリポジトリは変更しています。
”issueベース開発”までのレビューまでは、[このプロジェクト](https://github.com/users/rapidcplus/projects/1?pane=issue&itemId=60338571)で行なっていますが、
当アプリのリモートリポジトリはこちらの[ECS_４](https://github.com/rapidcplus/ECS_4
)です。_

※開発環境の構築やrailsのバージョンの違いによるエラー多発、デプロイ先の変更等で、合計で６回作り替えたことが要因で、都度issueをコピーし直すだけで、管理できていません。。。

## 各種情報
サービス名：Emergency_Call_Support
サービスURL：https://ecs-4.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
説明動画一覧画面: 様々な説明動画のサムネイルを表示
動画選択機能: ユーザーが状況に合った動画を選択
SMS送信機能: 選択した動画のURLをSMSで送信
検索機能: タイトル、タグ検索

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

- [x] Youtube shortsのみのURLを判別し、プレビュー表示させています。
- [x] 動画の埋め込み、サムネイル表示は実装しました。
- [x] 動画を選択することで、詳細画面や編集画面に飛ぶことができます。
- [ ] twilioAPIの実装によるSMS送信機能
- [ ] タグによる検索
- [ ] CSS（UIの向上）

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
- [x] 動画の種類がそこまで多くないと思い、タグや検索、ページネーションはつけていません。
- [x] Bootstrap => tailwindCSS　に変更
- [x] MYSQL => posgres　に変更 
- [x] デプロイ先にFly.ioを選定

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/41ffd100b1c9d447f01bc7ddb63a2d9e.png)](https://gyazo.com/41ffd100b1c9d447f01bc7ddb63a2d9e)

**Comment by Tsuchiya2** [comment]
https://github.com/rapidcplus/ECS_4/assets/61481161/935f07c9-f77d-4a5f-95f4-4b9a01165fa2

ログインできなくなったり、投稿したものが閲覧できなかったりと不具合やエラーが多発しているようですので、まずはそれらを修正していただけますでしょうか。

また、事前に投稿しておいたものを、どうやって他者と共有できるかの操作手順もコメント欄に説明書きをお願いいたします。

**Comment by rapidcplus** [comment]
> 2024-05-16.16.28.12.mov 
> ログインできなくなったり、投稿したものが閲覧できなかったりと不具合やエラーが多発しているようですので、まずはそれらを修正していただけますでしょうか。
> 
> また、事前に投稿しておいたものを、どうやって他者と共有できるかの操作手順もコメント欄に説明書きをお願いいたします。

お疲れ様です。不具合やエラーが多発しているとのこと大変失礼しました。確認と修正をしてみます。
また他者への共有は、SMS送信での共有のみです（未実装）。TwilioAPIの実装を検討しています。電話番号やトークン等はすでに取得しているものの、実装に苦戦しています。

**Comment by rapidcplus** [comment]
お世話になります。岩下です。
以前指摘を受けました不具合やエラーを修正しました。
またMVPリリース時に予定していたTwilioAPIについてですが、米国電話番号の取得に懸念があったため、他のSMS送信機能のAPI提供事業者を再考中しています。MVPリリース後に、API実装を予定しています。
※Twilio以外では株式会社ネクスウェイのSMSLinkを候補として挙げています。

[![Image from Gyazo](https://i.gyazo.com/a342e58d347bb1e669dc20f62d9ef3fa.png)](https://gyazo.com/a342e58d347bb1e669dc20f62d9ef3fa)

[![Image from Gyazo](https://i.gyazo.com/317ce6c1a5b041acb55768b429b40bc0.png)](https://gyazo.com/317ce6c1a5b041acb55768b429b40bc0)

レビューよろしくお願いします。

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
機能の修正、記述してある内容の実装は確認できました。
LGTMです。
